### ISSUE TITLE
Tags.IsSimulated not showingup

### ISSUE THREAD

**Issue by isaac73** [Azure/remote-monitoring-services-java#104]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Screenshot 

# Steps to reproduce 
1. Do a new RM deployment
2. Go to manage device group
3. add a new device group
4. look for Tags.IsSimulated

**Comment by elvinm** [comment]
PR is out for this fix here https://github.com/Azure/remote-monitoring-services-dotnet/pull/208 . Build wasn't working and failing on docker compose so it may not be in 2.1.1 release but the bug is smaller impact than expected anyway. The tags eventually show up once you start adding devices / doing other operations which refreshes the cache.

**Comment by ppathan** [comment]
Fixed
